version: "3"
services:
  user-app-client:
    build: ./frontend
    image: user-app-client-img
    container_name: user-app-client-cont
    stdin_open: true
    ports: 
      - "3000:3000"
    networks:
      - mern-app
    depends_on:
      - user-app-api
  user-app-api:
    build: ./api
    image: user-app-api-img
    container_name: user-app-api-cont
    ports:
      - "9000:9000"
    networks:
      - mern-app
    depends_on:
      - mongo
  mongo:
    image: mongo:3.6.19-xenial
    container_name: user-app-db-cont
    ports:
      - "27017:27017"
    networks:
      - mern-app
    volumes:
      - mongo-data:/data/db
networks:
  mern-app:
    driver: bridge
volumes:
  mongo-data:
    driver: local