version: "3"
services:
  user-app-frontend:
    build: ./frontend
    # image: user-app-frontend
    stdin_open: true
    ports: 
      - "3000:3000"
    networks:
      - mern-app
    depends_on:
      - user-app-api
  user-app-api:
    build: ./api
    # image: user-app-api
    ports:
      - "8000:8000"
    networks:
      - mern-app
    depends_on:
      - mongo
  mongo:
    image: mongo:3.6.19-xenial
    ports:
      - "27017:27017"
    networks:
      - mern-app
    volumes:
      - mongo-data:/data/db
networks:
  mern-app:
    driver: bridge
volumes:
  mongo-data:
    driver: local